[package]
name = "dataset"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
ommx = { path = "../ommx" }
zip.workspace = true
