# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import ommx
__all__ = [
    "constraint",
    "decision_variable",
    "function",
    "instance",
]

def constraint() -> ommx.Constraint: ...

def decision_variable() -> ommx.DecisionVariable: ...

def function() -> ommx.Function: ...

def instance() -> ommx.Instance: ...

