changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: Bug fix
      labels:
        - bug
    - title: Protobuf update
      labels:
        - proto
    - title: Python SDK update
      labels:
        - python
    - title: Rust SDK update
      labels:
        - rust
    - title: Documentation update
      labels:
        - documentation
    - title: Others
      labels:
        - "*"
