changelog:
  categories:
    - title: Protobuf update
      labels:
        - proto
    - title: Python SDK update
      labels:
        - python
    - title: ommx-python-mip-adapter update
      labels:
        - python-mip-adapter
    - title: Rust SDK update
      labels:
        - rust
    - title: Others
      labels:
        - "*"
