# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  api_reference:
    taskfile: docs/api_reference/Taskfile.yml
    dir: docs/api_reference
  book_ja:
    taskfile: docs/ja/Taskfile.yml
    dir: docs/ja
  book_en:
    taskfile: docs/en/Taskfile.yml
    dir: docs/en
  python:
    taskfile: python/Taskfile.yml
    dir: python
  rust:
    taskfile: rust/Taskfile.yml
    dir: rust
  proto:
    taskfile: proto/Taskfile.yml
    dir: proto

tasks:
  pip_compile:
    cmds:
      - uv pip compile pyproject.toml -o ../requirements.txt
    dir: docs/
