# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  api_reference:
    taskfile: docs/api_reference/Taskfile.yml
    dir: docs/api_reference
  book_ja:
    taskfile: docs/ja/Taskfile.yml
    dir: docs/ja
  book_en:
    taskfile: docs/en/Taskfile.yml
    dir: docs/en

tasks:

  doc_rust:
    cmds:
      - cargo doc --no-deps -p ommx

  doc_rust_open:
    cmds:
      - cargo doc --no-deps --open -p ommx

  # Protocol Buffers
  protogen:
    cmds:
      - task: protogen_python
      - task: protogen_rust

  protogen_python:
    cmds:
      - task: buf_generate_python
      - task: format_python

  protogen_rust:
    cmds:
      - cargo run --bin protogen

  buf_generate_python:
    cmds:
      - buf generate --template buf.gen.python.yaml
    dir: proto

  # Python
  install_python_sdk:
    cmds:
      - pip install -ve "python/ommx[dev]"

  install_python_mip_adapter:
    cmds:
      # Since python-mip for Apple Silicon is not available on PyPI, we need to install it from the source.
      - pip install git+https://github.com/coin-or/python-mip.git
      - pip install -ve "python/ommx-python-mip-adapter[dev]"

  install_pyscipopt_adapter:
    cmds:
      - pip install -ve "python/ommx-pyscipopt-adapter[dev]"

  install_openjij_adapter:
    cmds:
      - pip install -ve "python/ommx-openjij-adapter[dev]"

  install:
    cmds:
      - task: install_python_sdk
      - task: install_pyscipopt_adapter
      - task: install_openjij_adapter
      - task: install_python_mip_adapter

  format_python:
    cmds:
      - ruff format

  test_python:
    cmds:
      - task: test_python_sdk
      - task: test_python_mip_adapter
      - task: test_pyscipopt_adapter
      - task: test_openjij_adapter

  test_python_sdk:
    cmds:
      - pytest -vv --doctest-modules python/ommx/
      - pyright python/ommx/

  test_python_mip_adapter:
    cmds:
      - pytest -vv --doctest-modules python/ommx-python-mip-adapter/
      - markdown-code-runner python/ommx-python-mip-adapter/README.md
      - pyright python/ommx-python-mip-adapter/

  test_pyscipopt_adapter:
    cmds:
      - pytest -vv --doctest-modules python/ommx-pyscipopt-adapter/
      - markdown-code-runner python/ommx-pyscipopt-adapter/README.md
      - pyright python/ommx-pyscipopt-adapter/

  test_openjij_adapter:
    cmds:
      - pytest -vv --doctest-modules python/ommx-openjij-adapter/
      - pyright python/ommx-openjij-adapter/

  stubgen:
    cmds:
      - cargo run --bin stub_gen --features=stub_gen

  pip_compile:
    cmds:
      - uv pip compile pyproject.toml -o ../requirements.txt
    dir: docs/
