# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    cmds:
      - which ruff

  python_proto_gen:
    cmds:
      - task: buf_generate_python
      - task: ruff_format

  buf_generate_python:
    cmds:
      - buf generate --template buf.gen.python.yaml
    dir: proto

  ruff_format:
    cmds:
      - ruff format
