# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

includes:
  api_reference:
    taskfile: docs/api_reference/Taskfile.yml
    dir: docs/api_reference
  book_ja:
    taskfile: docs/ja/Taskfile.yml
    dir: docs/ja
  book_en:
    taskfile: docs/en/Taskfile.yml
    dir: docs/en
  python:
    taskfile: python/Taskfile.yml
    dir: python

tasks:
  doc_rust:
    cmds:
      - cargo doc --no-deps -p ommx

  doc_rust_open:
    cmds:
      - cargo doc --no-deps --open -p ommx

  # Protocol Buffers
  protogen:
    cmds:
      - task: protogen_python
      - task: protogen_rust

  protogen_python:
    cmds:
      - task: buf_generate_python
      - task: format_python

  protogen_rust:
    cmds:
      - cargo run --bin protogen

  buf_generate_python:
    cmds:
      - buf generate --template buf.gen.python.yaml
    dir: proto

  stubgen:
    cmds:
      - cargo run --bin stub_gen --features=stub_gen

  pip_compile:
    cmds:
      - uv pip compile pyproject.toml -o ../requirements.txt
    dir: docs/
