// This file is @generated by prost-build.
/// Named function row used by v2 top-level table owners.
///
/// The enclosing named-function table owns the NamedFunctionID and modeling
/// label sidecars. This row stores only the intrinsic expression payload.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamedFunction {
    #[prost(message, optional, tag = "1")]
    pub function: ::core::option::Option<super::v1::Function>,
}
