// This file is @generated by prost-build.
/// Human-authored modeling notation for one table or collection row.
///
/// This label preserves the mathematical model notation before the model was
/// lowered into OMMX. For example, a variable written as `x\[i, j\]` can be
/// represented as `name = "x"` and `subscripts = \[i, j\]`.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelingLabel {
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(int64, repeated, tag = "2")]
    pub subscripts: ::prost::alloc::vec::Vec<i64>,
    #[prost(btree_map = "string, string", tag = "3")]
    pub parameters: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(string, optional, tag = "4")]
    pub description: ::core::option::Option<::prost::alloc::string::String>,
}
/// Wire-level semantics required to interpret a top-level root exactly.
///
/// This is OMMX's feature-based forward-compatibility gate. Protobuf itself
/// preserves wire compatibility by letting older readers ignore unknown fields,
/// but that is not sufficient for mathematical optimization data: ignoring an
/// unknown constraint family or other semantic field can turn the payload into a
/// different problem. Top-level roots therefore declare the semantic features
/// required by the concrete payload.
///
/// Readers must reject payloads containing unknown, unsupported, or unspecified
/// `required_features`. Writers must include every feature whose omission would
/// let an older reader silently interpret a weaker or otherwise different model.
/// Writers must not emit `FEATURE_UNSPECIFIED` as a required feature.
#[non_exhaustive]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Feature {
    /// Placeholder for the protobuf default value. This is not a semantic feature.
    Unspecified = 0,
    /// The payload contains first-class indicator constraints.
    ConstraintIndicator = 1,
    /// The payload contains first-class one-hot constraints.
    ConstraintOneHot = 2,
    /// The payload contains first-class SOS1 constraints.
    ConstraintSos1 = 3,
    /// The payload contains a decision variable with an explicitly enumerated finite domain.
    DecisionVariableFiniteDomain = 4,
}
impl Feature {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Feature::Unspecified => "FEATURE_UNSPECIFIED",
            Feature::ConstraintIndicator => "FEATURE_CONSTRAINT_INDICATOR",
            Feature::ConstraintOneHot => "FEATURE_CONSTRAINT_ONE_HOT",
            Feature::ConstraintSos1 => "FEATURE_CONSTRAINT_SOS1",
            Feature::DecisionVariableFiniteDomain => "FEATURE_DECISION_VARIABLE_FINITE_DOMAIN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FEATURE_UNSPECIFIED" => Some(Self::Unspecified),
            "FEATURE_CONSTRAINT_INDICATOR" => Some(Self::ConstraintIndicator),
            "FEATURE_CONSTRAINT_ONE_HOT" => Some(Self::ConstraintOneHot),
            "FEATURE_CONSTRAINT_SOS1" => Some(Self::ConstraintSos1),
            "FEATURE_DECISION_VARIABLE_FINITE_DOMAIN" => Some(Self::DecisionVariableFiniteDomain),
            _ => None,
        }
    }
}
/// One transformation step in a constraint's lineage.
///
/// Provenance records special-constraint origins when a special constraint is
/// converted or propagated into another constraint family.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Provenance {
    #[prost(oneof = "provenance::Source", tags = "1, 2, 3")]
    pub source: ::core::option::Option<provenance::Source>,
}
/// Nested message and enum types in `Provenance`.
pub mod provenance {
    #[non_exhaustive]
    #[allow(clippy::derive_partial_eq_without_eq)]
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Source {
        #[prost(uint64, tag = "1")]
        IndicatorConstraintId(u64),
        #[prost(uint64, tag = "2")]
        OneHotConstraintId(u64),
        #[prost(uint64, tag = "3")]
        Sos1ConstraintId(u64),
    }
}
/// Constraint sidecar owned by one constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConstraintContext {
    #[prost(message, optional, tag = "1")]
    pub label: ::core::option::Option<ModelingLabel>,
    #[prost(message, repeated, tag = "2")]
    pub provenance: ::prost::alloc::vec::Vec<Provenance>,
}
/// Why a constraint row was removed or relaxed by preprocessing.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemovedReason {
    #[prost(string, tag = "1")]
    pub reason: ::prost::alloc::string::String,
    #[prost(btree_map = "string, string", tag = "2")]
    pub parameters: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Regular scalar constraint row.
///
/// The enclosing collection owns ConstraintID, modeling context, active/removed
/// placement, and removed reasons.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegularConstraint {
    #[prost(enumeration = "super::v1::Equality", tag = "1")]
    pub equality: i32,
    #[prost(message, optional, tag = "2")]
    pub function: ::core::option::Option<super::v1::Function>,
}
/// Indicator constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndicatorConstraint {
    #[prost(uint64, tag = "1")]
    pub indicator_variable: u64,
    #[prost(enumeration = "super::v1::Equality", tag = "2")]
    pub equality: i32,
    #[prost(message, optional, tag = "3")]
    pub function: ::core::option::Option<super::v1::Function>,
}
/// One-hot constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OneHotConstraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
}
/// SOS1 constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sos1Constraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
}
/// Regular constraint collection at the definition stage.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegularConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub active: ::prost::alloc::collections::BTreeMap<u64, RegularConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed: ::prost::alloc::collections::BTreeMap<u64, RegularConstraint>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "4")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Indicator constraint collection at the definition stage.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IndicatorConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub active: ::prost::alloc::collections::BTreeMap<u64, IndicatorConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed: ::prost::alloc::collections::BTreeMap<u64, IndicatorConstraint>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "4")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// One-hot constraint collection at the definition stage.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OneHotConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub active: ::prost::alloc::collections::BTreeMap<u64, OneHotConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed: ::prost::alloc::collections::BTreeMap<u64, OneHotConstraint>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "4")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// SOS1 constraint collection at the definition stage.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Sos1ConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub active: ::prost::alloc::collections::BTreeMap<u64, Sos1Constraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed: ::prost::alloc::collections::BTreeMap<u64, Sos1Constraint>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "4")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Evaluated regular constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedRegularConstraint {
    #[prost(enumeration = "super::v1::Equality", tag = "1")]
    pub equality: i32,
    #[prost(double, tag = "2")]
    pub evaluated_value: f64,
    #[prost(bool, tag = "3")]
    pub feasible: bool,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(double, optional, tag = "5")]
    pub dual_variable: ::core::option::Option<f64>,
}
/// Evaluated indicator constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedIndicatorConstraint {
    #[prost(uint64, tag = "1")]
    pub indicator_variable: u64,
    #[prost(enumeration = "super::v1::Equality", tag = "2")]
    pub equality: i32,
    #[prost(double, tag = "3")]
    pub evaluated_value: f64,
    #[prost(bool, tag = "4")]
    pub feasible: bool,
    #[prost(bool, tag = "5")]
    pub indicator_active: bool,
    #[prost(uint64, repeated, tag = "6")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Evaluated one-hot constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedOneHotConstraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, tag = "2")]
    pub feasible: bool,
    #[prost(uint64, optional, tag = "3")]
    pub active_variable: ::core::option::Option<u64>,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Evaluated SOS1 constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedSos1Constraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
    #[prost(bool, tag = "2")]
    pub feasible: bool,
    #[prost(uint64, optional, tag = "3")]
    pub active_variable: ::core::option::Option<u64>,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Evaluated regular constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedRegularConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedRegularConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Evaluated indicator constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedIndicatorConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedIndicatorConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Evaluated one-hot constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedOneHotConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedOneHotConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Evaluated SOS1 constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedSos1ConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedSos1Constraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Map value used when a present sample can have no active variable.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledActiveVariable {
    #[prost(uint64, optional, tag = "1")]
    pub variable_id: ::core::option::Option<u64>,
}
/// Sampled regular constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledRegularConstraint {
    #[prost(enumeration = "super::v1::Equality", tag = "1")]
    pub equality: i32,
    #[prost(message, optional, tag = "2")]
    pub evaluated_values: ::core::option::Option<super::v1::SampledValues>,
    #[prost(btree_map = "uint64, bool", tag = "3")]
    pub feasible: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(message, optional, tag = "5")]
    pub dual_variables: ::core::option::Option<super::v1::SampledValues>,
}
/// Sampled indicator constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledIndicatorConstraint {
    #[prost(uint64, tag = "1")]
    pub indicator_variable: u64,
    #[prost(enumeration = "super::v1::Equality", tag = "2")]
    pub equality: i32,
    #[prost(message, optional, tag = "3")]
    pub evaluated_values: ::core::option::Option<super::v1::SampledValues>,
    #[prost(btree_map = "uint64, bool", tag = "4")]
    pub feasible: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(btree_map = "uint64, bool", tag = "5")]
    pub indicator_active: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(uint64, repeated, tag = "6")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Sampled one-hot constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledOneHotConstraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
    #[prost(btree_map = "uint64, bool", tag = "2")]
    pub feasible: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub active_variable: ::prost::alloc::collections::BTreeMap<u64, SampledActiveVariable>,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Sampled SOS1 constraint row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledSos1Constraint {
    #[prost(uint64, repeated, tag = "1")]
    pub variables: ::prost::alloc::vec::Vec<u64>,
    #[prost(btree_map = "uint64, bool", tag = "2")]
    pub feasible: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub active_variable: ::prost::alloc::collections::BTreeMap<u64, SampledActiveVariable>,
    #[prost(uint64, repeated, tag = "4")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Sampled regular constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledRegularConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledRegularConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Sampled indicator constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledIndicatorConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledIndicatorConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Sampled one-hot constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledOneHotConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledOneHotConstraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Sampled SOS1 constraint collection.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledSos1ConstraintCollection {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledSos1Constraint>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub removed_reasons: ::prost::alloc::collections::BTreeMap<u64, RemovedReason>,
    #[prost(btree_map = "uint64, message", tag = "3")]
    pub contexts: ::prost::alloc::collections::BTreeMap<u64, ConstraintContext>,
}
/// Definition-stage decision-variable row.
///
/// The enclosing DecisionVariableTable owns VariableID and modeling labels.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionVariable {
    #[prost(enumeration = "super::v1::decision_variable::Kind", tag = "1")]
    pub kind: i32,
    /// Required for interval-domain kinds and absent for KIND_FINITE_DOMAIN.
    #[prost(message, optional, tag = "2")]
    pub bound: ::core::option::Option<super::v1::Bound>,
    /// Required for KIND_FINITE_DOMAIN and absent for interval-domain kinds.
    #[prost(message, optional, tag = "3")]
    pub finite_domain: ::core::option::Option<super::v1::FiniteDomain>,
}
/// Evaluated-stage decision-variable row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedDecisionVariable {
    #[prost(enumeration = "super::v1::decision_variable::Kind", tag = "1")]
    pub kind: i32,
    /// Required for interval-domain kinds and absent for KIND_FINITE_DOMAIN.
    #[prost(message, optional, tag = "2")]
    pub bound: ::core::option::Option<super::v1::Bound>,
    #[prost(double, tag = "3")]
    pub value: f64,
    /// Required for KIND_FINITE_DOMAIN and absent for interval-domain kinds.
    #[prost(message, optional, tag = "4")]
    pub finite_domain: ::core::option::Option<super::v1::FiniteDomain>,
}
/// Sampled-stage decision-variable row.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledDecisionVariable {
    #[prost(enumeration = "super::v1::decision_variable::Kind", tag = "1")]
    pub kind: i32,
    /// Required for interval-domain kinds and absent for KIND_FINITE_DOMAIN.
    #[prost(message, optional, tag = "2")]
    pub bound: ::core::option::Option<super::v1::Bound>,
    #[prost(message, optional, tag = "3")]
    pub samples: ::core::option::Option<super::v1::SampledValues>,
    /// Required for KIND_FINITE_DOMAIN and absent for interval-domain kinds.
    #[prost(message, optional, tag = "4")]
    pub finite_domain: ::core::option::Option<super::v1::FiniteDomain>,
}
/// Definition-stage decision-variable table.
///
/// Map keys own VariableID. `labels` and `fixed_values` must only reference
/// IDs present in `entries`.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionVariableTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, DecisionVariable>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
    #[prost(btree_map = "uint64, double", tag = "3")]
    pub fixed_values: ::prost::alloc::collections::BTreeMap<u64, f64>,
}
/// Evaluated-stage decision-variable table.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedDecisionVariableTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedDecisionVariable>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Sampled-stage decision-variable table.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledDecisionVariableTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledDecisionVariable>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Named function row used by v2 top-level table owners.
///
/// The enclosing named-function table owns the NamedFunctionID and modeling
/// label sidecars. This row stores only the intrinsic expression payload.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamedFunction {
    #[prost(message, optional, tag = "1")]
    pub function: ::core::option::Option<super::v1::Function>,
}
/// Evaluated named-function row used by v2 top-level table owners.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedNamedFunction {
    #[prost(double, tag = "1")]
    pub evaluated_value: f64,
    #[prost(uint64, repeated, tag = "2")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Sampled named-function row used by v2 top-level table owners.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledNamedFunction {
    #[prost(message, optional, tag = "1")]
    pub evaluated_values: ::core::option::Option<super::v1::SampledValues>,
    #[prost(uint64, repeated, tag = "2")]
    pub used_decision_variable_ids: ::prost::alloc::vec::Vec<u64>,
}
/// Definition-stage named-function table.
///
/// Map keys own NamedFunctionID. `labels` must only reference IDs present in
/// `entries`.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NamedFunctionTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, NamedFunction>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Evaluated-stage named-function table.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EvaluatedNamedFunctionTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, EvaluatedNamedFunction>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Sampled-stage named-function table.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampledNamedFunctionTable {
    #[prost(btree_map = "uint64, message", tag = "1")]
    pub entries: ::prost::alloc::collections::BTreeMap<u64, SampledNamedFunction>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Validated optimization problem serialization root.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Instance {
    #[prost(enumeration = "Feature", repeated, tag = "1")]
    pub required_features: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "2")]
    pub description: ::core::option::Option<super::v1::instance::Description>,
    #[prost(message, optional, tag = "3")]
    pub decision_variables: ::core::option::Option<DecisionVariableTable>,
    #[prost(message, optional, tag = "4")]
    pub objective: ::core::option::Option<super::v1::Function>,
    #[prost(message, optional, tag = "5")]
    pub regular_constraints: ::core::option::Option<RegularConstraintCollection>,
    #[prost(enumeration = "super::v1::instance::Sense", tag = "6")]
    pub sense: i32,
    #[prost(message, optional, tag = "7")]
    pub parameters: ::core::option::Option<super::v1::Parameters>,
    #[prost(message, optional, tag = "8")]
    pub indicator_constraints: ::core::option::Option<IndicatorConstraintCollection>,
    #[prost(message, optional, tag = "9")]
    pub one_hot_constraints: ::core::option::Option<OneHotConstraintCollection>,
    #[prost(message, optional, tag = "10")]
    pub sos1_constraints: ::core::option::Option<Sos1ConstraintCollection>,
    #[prost(btree_map = "uint64, message", tag = "11")]
    pub decision_variable_dependency:
        ::prost::alloc::collections::BTreeMap<u64, super::v1::Function>,
    #[prost(message, optional, tag = "12")]
    pub named_functions: ::core::option::Option<NamedFunctionTable>,
    #[prost(btree_map = "string, string", tag = "13")]
    pub annotations: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Parameter IDs and labels owned by ParametricInstance.
///
/// Parameter IDs intentionally share the VariableID namespace with decision
/// variables. ParametricInstance validates disjointness.
///
/// `ids` is a set encoded as a repeated field. IDs must be unique, and `labels`
/// must only reference IDs present in `ids`.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParameterTable {
    #[prost(uint64, repeated, tag = "1")]
    pub ids: ::prost::alloc::vec::Vec<u64>,
    #[prost(btree_map = "uint64, message", tag = "2")]
    pub labels: ::prost::alloc::collections::BTreeMap<u64, ModelingLabel>,
}
/// Validated parametric optimization problem serialization root.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParametricInstance {
    #[prost(enumeration = "Feature", repeated, tag = "1")]
    pub required_features: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "2")]
    pub description: ::core::option::Option<super::v1::instance::Description>,
    #[prost(message, optional, tag = "3")]
    pub decision_variables: ::core::option::Option<DecisionVariableTable>,
    #[prost(message, optional, tag = "4")]
    pub parameters: ::core::option::Option<ParameterTable>,
    #[prost(message, optional, tag = "5")]
    pub objective: ::core::option::Option<super::v1::Function>,
    #[prost(message, optional, tag = "6")]
    pub regular_constraints: ::core::option::Option<RegularConstraintCollection>,
    #[prost(enumeration = "super::v1::instance::Sense", tag = "7")]
    pub sense: i32,
    #[prost(message, optional, tag = "8")]
    pub indicator_constraints: ::core::option::Option<IndicatorConstraintCollection>,
    #[prost(message, optional, tag = "9")]
    pub one_hot_constraints: ::core::option::Option<OneHotConstraintCollection>,
    #[prost(message, optional, tag = "10")]
    pub sos1_constraints: ::core::option::Option<Sos1ConstraintCollection>,
    #[prost(btree_map = "uint64, message", tag = "11")]
    pub decision_variable_dependency:
        ::prost::alloc::collections::BTreeMap<u64, super::v1::Function>,
    #[prost(message, optional, tag = "12")]
    pub named_functions: ::core::option::Option<NamedFunctionTable>,
    #[prost(btree_map = "string, string", tag = "13")]
    pub annotations: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// Validated multi-sample solver or sampler output serialization root.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SampleSet {
    #[prost(enumeration = "Feature", repeated, tag = "1")]
    pub required_features: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "2")]
    pub objectives: ::core::option::Option<super::v1::SampledValues>,
    #[prost(message, optional, tag = "3")]
    pub decision_variables: ::core::option::Option<SampledDecisionVariableTable>,
    #[prost(message, optional, tag = "4")]
    pub sampled_regular_constraints: ::core::option::Option<SampledRegularConstraintCollection>,
    #[prost(btree_map = "uint64, bool", tag = "5")]
    pub feasible: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(enumeration = "super::v1::instance::Sense", tag = "6")]
    pub sense: i32,
    #[prost(btree_map = "uint64, bool", tag = "7")]
    pub feasible_relaxed: ::prost::alloc::collections::BTreeMap<u64, bool>,
    #[prost(message, optional, tag = "8")]
    pub sampled_named_functions: ::core::option::Option<SampledNamedFunctionTable>,
    #[prost(message, optional, tag = "9")]
    pub metadata: ::core::option::Option<super::v1::ProcessMetadata>,
    #[prost(btree_map = "string, string", tag = "10")]
    pub annotations: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "11")]
    pub sampled_indicator_constraints: ::core::option::Option<SampledIndicatorConstraintCollection>,
    #[prost(message, optional, tag = "12")]
    pub sampled_one_hot_constraints: ::core::option::Option<SampledOneHotConstraintCollection>,
    #[prost(message, optional, tag = "13")]
    pub sampled_sos1_constraints: ::core::option::Option<SampledSos1ConstraintCollection>,
    /// Absolute tolerance used to compute and validate `feasible`,
    /// `feasible_relaxed`, and per-constraint feasibility columns.
    #[prost(double, optional, tag = "14")]
    pub feasibility_atol: ::core::option::Option<f64>,
}
/// Validated single-state solver output serialization root.
#[non_exhaustive]
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Solution {
    #[prost(enumeration = "Feature", repeated, tag = "1")]
    pub required_features: ::prost::alloc::vec::Vec<i32>,
    #[prost(double, tag = "2")]
    pub objective: f64,
    #[prost(message, optional, tag = "3")]
    pub decision_variables: ::core::option::Option<EvaluatedDecisionVariableTable>,
    #[prost(message, optional, tag = "4")]
    pub evaluated_regular_constraints: ::core::option::Option<EvaluatedRegularConstraintCollection>,
    #[prost(bool, tag = "5")]
    pub feasible: bool,
    #[prost(enumeration = "super::v1::Optimality", tag = "6")]
    pub optimality: i32,
    #[prost(enumeration = "super::v1::Relaxation", tag = "7")]
    pub relaxation: i32,
    #[prost(bool, optional, tag = "8")]
    pub feasible_relaxed: ::core::option::Option<bool>,
    #[prost(enumeration = "super::v1::instance::Sense", tag = "9")]
    pub sense: i32,
    #[prost(message, optional, tag = "10")]
    pub evaluated_named_functions: ::core::option::Option<EvaluatedNamedFunctionTable>,
    #[prost(message, optional, tag = "11")]
    pub metadata: ::core::option::Option<super::v1::ProcessMetadata>,
    #[prost(btree_map = "string, string", tag = "12")]
    pub annotations: ::prost::alloc::collections::BTreeMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, optional, tag = "13")]
    pub evaluated_indicator_constraints:
        ::core::option::Option<EvaluatedIndicatorConstraintCollection>,
    #[prost(message, optional, tag = "14")]
    pub evaluated_one_hot_constraints: ::core::option::Option<EvaluatedOneHotConstraintCollection>,
    #[prost(message, optional, tag = "15")]
    pub evaluated_sos1_constraints: ::core::option::Option<EvaluatedSos1ConstraintCollection>,
    /// Absolute tolerance used to compute and validate `feasible`,
    /// `feasible_relaxed`, and per-constraint feasibility columns.
    #[prost(double, optional, tag = "16")]
    pub feasibility_atol: ::core::option::Option<f64>,
}
