use crate::pandas::{entries_to_dataframe, PyDataFrame};
use anyhow::Result;
use pyo3::{
    exceptions::PyKeyError,
    exceptions::PyRuntimeError,
    prelude::*,
    types::{PyBytes, PyDict, PyTuple},
    Bound,
};
use std::collections::{BTreeSet, HashMap};

/// Idiomatic wrapper of `ommx.v1.Solution` protobuf message.
///
/// This also contains annotations not contained in protobuf message, and will be stored in OMMX artifact.
#[pyo3_stub_gen::derive::gen_stub_pyclass]
#[pyclass]
#[derive(Clone)]
pub struct Solution {
    pub(crate) inner: ommx::Solution,
    pub(crate) annotations: HashMap<String, String>,
}

crate::annotations::impl_solution_annotations!(Solution, "org.ommx.v1.solution");

#[pyo3_stub_gen::derive::gen_stub_pymethods]
#[pymethods]
impl Solution {
    #[staticmethod]
    pub fn from_bytes(bytes: &Bound<PyBytes>) -> Result<Self> {
        Ok(Self {
            inner: ommx::Solution::from_bytes(bytes.as_bytes())?,
            annotations: HashMap::new(),
        })
    }

    pub fn to_bytes<'py>(&self, py: Python<'py>) -> Bound<'py, PyBytes> {
        PyBytes::new(py, &self.inner.to_bytes())
    }

    /// Class constant for optimal solutions
    #[classattr]
    #[pyo3(name = "OPTIMAL")]
    fn class_optimal() -> crate::Optimality {
        crate::Optimality::Optimal
    }

    /// Class constant for non-optimal solutions
    #[classattr]
    #[pyo3(name = "NOT_OPTIMAL")]
    fn class_not_optimal() -> crate::Optimality {
        crate::Optimality::NotOptimal
    }

    /// Class constant for LP-relaxed solutions
    #[classattr]
    #[pyo3(name = "LP_RELAXED")]
    fn class_lp_relaxed() -> crate::Relaxation {
        crate::Relaxation::LpRelaxed
    }

    /// Get the objective function value
    #[getter]
    pub fn objective(&self) -> f64 {
        *self.inner.objective()
    }

    /// Get the solution state containing variable values
    #[getter]
    pub fn state(&self) -> crate::State {
        crate::State(self.inner.state())
    }

    /// Feasibility of the solution in terms of all constraints, including removed constraints.
    ///
    /// This is an alias for `feasible_unrelaxed`.
    ///
    /// Compatibility: The meaning of this property has changed from Python SDK 1.7.0.
    /// Previously, this property represents the feasibility of the remaining constraints only,
    /// i.e. excluding relaxed constraints.
    /// From Python SDK 1.7.0, this property represents the feasibility of all constraints,
    /// including relaxed constraints.
    #[getter]
    pub fn feasible(&self) -> bool {
        // The `feasible` means feasible in the unrelaxed problem
        self.inner.feasible()
    }

    /// Feasibility of the solution in terms of remaining constraints, not including relaxed (removed) constraints.
    #[getter]
    pub fn feasible_relaxed(&self) -> bool {
        self.inner.feasible_relaxed()
    }

    /// Feasibility of the solution in terms of all constraints, including relaxed (removed) constraints.
    #[getter]
    pub fn feasible_unrelaxed(&self) -> bool {
        self.inner.feasible()
    }

    /// Get the optimization sense (minimize or maximize)
    #[getter]
    pub fn sense(&self) -> Result<crate::Sense> {
        let sense = (*self.inner.sense()).ok_or_else(|| {
            PyRuntimeError::new_err(
                "This property is available for ommx.v1.Solution generated by OMMX v2.0.0 or later."
            )
        })?;
        Ok(sense.into())
    }

    /// Get the optimality status
    #[getter]
    pub fn optimality(&self) -> crate::Optimality {
        self.inner.optimality.into()
    }

    /// Get the relaxation status
    #[getter]
    pub fn relaxation(&self) -> crate::Relaxation {
        self.inner.relaxation.into()
    }

    /// Set the optimality status
    #[setter]
    pub fn set_optimality(&mut self, optimality: crate::Optimality) {
        self.inner.optimality = optimality.into();
    }

    /// Set the relaxation status
    #[setter]
    pub fn set_relaxation(&mut self, relaxation: crate::Relaxation) {
        self.inner.relaxation = relaxation.into();
    }

    /// Get evaluated decision variables as a list sorted by ID
    #[getter]
    pub fn decision_variables(&self) -> Vec<crate::EvaluatedDecisionVariable> {
        // BTreeMap is already sorted by key
        self.inner
            .decision_variables()
            .values()
            .map(|dv| crate::EvaluatedDecisionVariable(dv.clone()))
            .collect()
    }

    /// Get evaluated constraints as a dict keyed by constraint ID
    #[getter]
    pub fn constraints(&self) -> std::collections::BTreeMap<u64, crate::EvaluatedConstraint> {
        self.inner
            .evaluated_constraints()
            .iter()
            .map(|(id, ec)| (id.into_inner(), crate::EvaluatedConstraint(ec.clone())))
            .collect()
    }

    /// Get evaluated named functions as a list sorted by ID
    #[getter]
    pub fn named_functions(&self) -> Vec<crate::EvaluatedNamedFunction> {
        self.inner
            .evaluated_named_functions()
            .values()
            .map(|nf| crate::EvaluatedNamedFunction(nf.clone()))
            .collect()
    }

    #[getter]
    pub fn decision_variable_ids(&self) -> BTreeSet<u64> {
        self.inner
            .decision_variable_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    #[getter]
    pub fn constraint_ids(&self) -> BTreeSet<u64> {
        self.inner
            .constraint_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    /// Get all unique decision variable names in this solution.
    ///
    /// Returns a set of all unique variable names. Variables without names are not included.
    ///
    /// # Examples
    ///
    /// ```python
    /// >>> from ommx.v1 import Instance, DecisionVariable
    /// >>> x = [DecisionVariable.binary(i, name="x", subscripts=[i]) for i in range(3)]
    /// >>> y = [DecisionVariable.binary(i+3, name="y", subscripts=[i]) for i in range(2)]
    /// >>> instance = Instance.from_components(
    /// ...     decision_variables=x + y,
    /// ...     objective=sum(x) + sum(y),
    /// ...     constraints=[],
    /// ...     sense=Instance.MAXIMIZE,
    /// ... )
    /// >>> solution = instance.evaluate({i: 1 for i in range(5)})
    /// >>> sorted(solution.decision_variable_names)
    /// ['x', 'y']
    /// ```
    #[getter]
    pub fn decision_variable_names(&self) -> BTreeSet<String> {
        self.inner.decision_variable_names()
    }

    #[getter]
    pub fn named_function_ids(&self) -> BTreeSet<u64> {
        self.inner
            .named_function_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    /// Get all unique named function names in this solution
    #[getter]
    pub fn named_function_names(&self) -> BTreeSet<String> {
        self.inner.named_function_names()
    }

    /// Extract the values of decision variables based on the `name` with `subscripts` key.
    ///
    /// Raises ValueError if a decision variable with parameters is found, or if the same subscript is found.
    ///
    /// # Examples
    ///
    /// ```python
    /// >>> from ommx.v1 import Instance, DecisionVariable
    /// >>> x = [DecisionVariable.binary(i, name="x", subscripts=[i]) for i in range(3)]
    /// >>> instance = Instance.from_components(
    /// ...     decision_variables=x,
    /// ...     objective=sum(x),
    /// ...     constraints=[sum(x) == 1],
    /// ...     sense=Instance.MAXIMIZE,
    /// ... )
    /// >>> solution = instance.evaluate({i: 1 for i in range(3)})
    /// >>> solution.extract_decision_variables("x")
    /// {(0,): 1.0, (1,): 1.0, (2,): 1.0}
    /// ```
    pub fn extract_decision_variables<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_decision_variables(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract all decision variables grouped by name.
    ///
    /// Returns a mapping from variable name to a mapping from subscripts to values.
    /// This is useful for extracting all variables at once in a structured format.
    /// Variables without names are not included in the result.
    ///
    /// Raises ValueError if a decision variable with parameters is found, or if the same
    /// name and subscript combination is found multiple times.
    ///
    /// # Examples
    ///
    /// ```python
    /// >>> from ommx.v1 import Instance, DecisionVariable
    /// >>> x = [DecisionVariable.binary(i, name="x", subscripts=[i]) for i in range(3)]
    /// >>> y = [DecisionVariable.binary(i+3, name="y", subscripts=[i]) for i in range(2)]
    /// >>> instance = Instance.from_components(
    /// ...     decision_variables=x + y,
    /// ...     objective=sum(x) + sum(y),
    /// ...     constraints=[],
    /// ...     sense=Instance.MAXIMIZE,
    /// ... )
    /// >>> solution = instance.evaluate({i: 1 for i in range(5)})
    /// >>> all_vars = solution.extract_all_decision_variables()
    /// >>> all_vars["x"]
    /// {(0,): 1.0, (1,): 1.0, (2,): 1.0}
    /// >>> all_vars["y"]
    /// {(0,): 1.0, (1,): 1.0}
    /// ```
    pub fn extract_all_decision_variables<'py>(
        &self,
        py: Python<'py>,
    ) -> Result<Bound<'py, PyDict>> {
        let result_dict = PyDict::new(py);
        for (name, variables) in self.inner.extract_all_decision_variables()? {
            let var_dict = PyDict::new(py);
            for (subscripts, value) in variables {
                let key_tuple = PyTuple::new(py, &subscripts)?;
                var_dict.set_item(key_tuple, value)?;
            }
            result_dict.set_item(name, var_dict)?;
        }
        Ok(result_dict)
    }

    /// Extract the values of constraints based on the `name` with `subscripts` key.
    ///
    /// Raises ValueError if the constraint with parameters is found, or if the same subscript is found.
    ///
    /// # Examples
    ///
    /// ```python
    /// >>> from ommx.v1 import Instance, DecisionVariable
    /// >>> x = [DecisionVariable.binary(i) for i in range(3)]
    /// >>> c0 = (x[0] + x[1] == 1).add_name("c").add_subscripts([0])
    /// >>> c1 = (x[1] + x[2] == 1).add_name("c").add_subscripts([1])
    /// >>> instance = Instance.from_components(
    /// ...     decision_variables=x,
    /// ...     objective=sum(x),
    /// ...     constraints=[c0, c1],
    /// ...     sense=Instance.MAXIMIZE,
    /// ... )
    /// >>> solution = instance.evaluate({0: 1, 1: 0, 2: 1})
    /// >>> solution.extract_constraints("c")
    /// {(0,): 0.0, (1,): 0.0}
    /// ```
    pub fn extract_constraints<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_constraints(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract named functions by name with subscripts as key (returns a Python dict)
    pub fn extract_named_functions<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_named_functions(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract all named functions grouped by name (returns a Python dict)
    pub fn extract_all_named_functions<'py>(&self, py: Python<'py>) -> Result<Bound<'py, PyDict>> {
        let result_dict = PyDict::new(py);
        for (name, functions) in self.inner.extract_all_named_functions()? {
            let func_dict = PyDict::new(py);
            for (subscripts, value) in functions {
                let key_tuple = PyTuple::new(py, &subscripts)?;
                func_dict.set_item(key_tuple, value)?;
            }
            result_dict.set_item(name, func_dict)?;
        }
        Ok(result_dict)
    }

    /// Set the dual variable value for a specific constraint by ID
    pub fn set_dual_variable(&mut self, constraint_id: u64, value: Option<f64>) -> PyResult<()> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .set_dual_variable(constraint_id, value)
            .map_err(|e| PyKeyError::new_err(e.to_string()))
    }

    /// Get a specific evaluated decision variable by ID
    pub fn get_decision_variable_by_id(
        &self,
        variable_id: u64,
    ) -> PyResult<crate::EvaluatedDecisionVariable> {
        let var_id = ommx::VariableID::from(variable_id);
        self.inner
            .decision_variables()
            .get(&var_id)
            .map(|dv| crate::EvaluatedDecisionVariable(dv.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!("Unknown decision variable ID: {variable_id}"))
            })
    }

    /// Get the evaluated value of a specific constraint by ID
    pub fn get_constraint_value(&self, constraint_id: u64) -> PyResult<f64> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .evaluated_constraints()
            .get(&constraint_id)
            .map(|ec| ec.stage.evaluated_value)
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown constraint ID: {}",
                    constraint_id.into_inner()
                ))
            })
    }

    /// Get the dual variable value for a specific constraint by ID
    pub fn get_dual_variable(&self, constraint_id: u64) -> PyResult<Option<f64>> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .evaluated_constraints()
            .get(&constraint_id)
            .map(|ec| ec.stage.dual_variable)
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown constraint ID: {}",
                    constraint_id.into_inner()
                ))
            })
    }

    /// Get a specific evaluated constraint by ID
    pub fn get_constraint_by_id(&self, constraint_id: u64) -> PyResult<crate::EvaluatedConstraint> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .evaluated_constraints()
            .get(&constraint_id)
            .map(|ec| crate::EvaluatedConstraint(ec.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown constraint ID: {}",
                    constraint_id.into_inner()
                ))
            })
    }

    /// Get a specific evaluated named function by ID
    pub fn get_named_function_by_id(
        &self,
        named_function_id: u64,
    ) -> PyResult<crate::EvaluatedNamedFunction> {
        let named_function_id = ommx::NamedFunctionID::from(named_function_id);
        self.inner
            .evaluated_named_functions()
            .get(&named_function_id)
            .map(|nf| crate::EvaluatedNamedFunction(nf.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown named function ID: {}",
                    named_function_id.into_inner()
                ))
            })
    }

    /// DataFrame of evaluated decision variables
    ///
    /// Columns: id (index), kind, lower, upper, name, subscripts, description, substituted_value, value
    #[getter]
    pub fn decision_variables_df<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(py, self.inner.decision_variables().values(), "id")
    }

    /// DataFrame of evaluated constraints
    ///
    /// Columns: id (index), equality, value, used_ids, name, subscripts, description, dual_variable
    #[getter]
    pub fn constraints_df<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_constraints()
                .iter()
                .map(|(id, c)| (*id, c)),
            "id",
        )
    }

    /// DataFrame of removed constraint reasons.
    ///
    /// Columns: id (index), removed_reason, removed_reason.{key}
    ///
    /// Can be joined with {attr}`constraints_df` on the `id` index.
    ///
    /// # Examples
    ///
    /// ```python
    /// >>> from ommx.v1 import Instance, DecisionVariable
    /// >>> x = [DecisionVariable.binary(i) for i in range(3)]
    /// >>> instance = Instance.from_components(
    /// ...     decision_variables=x,
    /// ...     objective=sum(x),
    /// ...     constraints=[
    /// ...         (x[0] + x[1] == 1).set_id(10),
    /// ...         (x[1] + x[2] == 1).set_id(20),
    /// ...     ],
    /// ...     sense=Instance.MAXIMIZE,
    /// ... )
    /// >>> instance.relax_constraint(10, "test_reason")
    /// >>> solution = instance.evaluate({0: 1, 1: 0, 2: 1})
    /// ```
    ///
    /// `removed_reasons_df` contains only removed constraints:
    ///
    /// ```python
    /// >>> solution.removed_reasons_df
    ///     removed_reason
    /// id
    /// 10    test_reason
    /// ```
    ///
    /// Join with `constraints_df` to get full information:
    ///
    /// ```python
    /// >>> df = solution.constraints_df.join(solution.removed_reasons_df)
    /// >>> df[["value", "removed_reason"]]
    ///     value removed_reason
    /// id
    /// 10    0.0   test_reason
    /// 20    0.0           NaN
    /// ```
    #[getter]
    pub fn removed_reasons_df<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDataFrame>> {
        use crate::pandas::RemovedReasonEntry;
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_constraints()
                .removed_reasons()
                .iter()
                .map(|(id, reason)| RemovedReasonEntry {
                    id: id.into_inner(),
                    reason,
                }),
            "id",
        )
    }

    /// DataFrame of evaluated indicator constraints
    ///
    /// Columns: id (index), indicator_variable_id, equality, value, indicator_active, used_ids, name, subscripts, description
    #[getter]
    pub fn indicator_constraints_df<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_indicator_constraints()
                .iter()
                .map(|(id, c)| (*id, c)),
            "id",
        )
    }

    /// DataFrame of removed indicator constraint reasons.
    ///
    /// Columns: id (index), removed_reason, removed_reason.{key}
    ///
    /// Can be joined with {attr}`indicator_constraints_df` using the `id` index.
    #[getter]
    pub fn indicator_removed_reasons_df<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyDataFrame>> {
        use crate::pandas::RemovedReasonEntry;
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_indicator_constraints()
                .removed_reasons()
                .iter()
                .map(|(id, reason)| RemovedReasonEntry {
                    id: id.into_inner(),
                    reason,
                }),
            "id",
        )
    }

    /// DataFrame of evaluated one-hot constraints
    ///
    /// Columns: id (index), feasible, active_variable, used_ids, name, subscripts, description
    #[getter]
    pub fn one_hot_constraints_df<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_one_hot_constraints()
                .iter()
                .map(|(id, c)| (*id, c)),
            "id",
        )
    }

    /// DataFrame of removed one-hot constraint reasons.
    ///
    /// Columns: id (index), removed_reason, removed_reason.{key}
    ///
    /// Can be joined with {attr}`one_hot_constraints_df` using the `id` index.
    #[getter]
    pub fn one_hot_removed_reasons_df<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyDataFrame>> {
        use crate::pandas::RemovedReasonEntry;
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_one_hot_constraints()
                .removed_reasons()
                .iter()
                .map(|(id, reason)| RemovedReasonEntry {
                    id: id.into_inner(),
                    reason,
                }),
            "id",
        )
    }

    /// DataFrame of evaluated SOS1 constraints
    ///
    /// Columns: id (index), feasible, active_variable, used_ids, name, subscripts, description
    #[getter]
    pub fn sos1_constraints_df<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_sos1_constraints()
                .iter()
                .map(|(id, c)| (*id, c)),
            "id",
        )
    }

    /// DataFrame of removed SOS1 constraint reasons.
    ///
    /// Columns: id (index), removed_reason, removed_reason.{key}
    ///
    /// Can be joined with {attr}`sos1_constraints_df` using the `id` index.
    #[getter]
    pub fn sos1_removed_reasons_df<'py>(
        &self,
        py: Python<'py>,
    ) -> PyResult<Bound<'py, PyDataFrame>> {
        use crate::pandas::RemovedReasonEntry;
        entries_to_dataframe(
            py,
            self.inner
                .evaluated_sos1_constraints()
                .removed_reasons()
                .iter()
                .map(|(id, reason)| RemovedReasonEntry {
                    id: id.into_inner(),
                    reason,
                }),
            "id",
        )
    }

    /// DataFrame of evaluated named functions
    ///
    /// Columns: id (index), value, used_ids, name, subscripts, description, parameters.{key}
    #[getter]
    pub fn named_functions_df<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyDataFrame>> {
        entries_to_dataframe(py, self.inner.evaluated_named_functions().values(), "id")
    }

    fn __copy__(&self) -> Self {
        self.clone()
    }

    fn __deepcopy__(&self, _memo: Bound<'_, PyAny>) -> Self {
        self.clone()
    }

    /// Calculate total constraint violation using L1 norm (sum of absolute violations)
    ///
    /// Returns the sum of violations across all constraints (including removed constraints):
    /// - For equality constraints: $\sum |f(x)|$
    /// - For inequality constraints: $\sum \max(0, f(x))$
    pub fn total_violation_l1(&self) -> f64 {
        self.inner.total_violation_l1()
    }

    /// Calculate total constraint violation using L2 norm squared (sum of squared violations)
    ///
    /// Returns the sum of squared violations across all constraints (including removed constraints):
    /// - For equality constraints: $\sum (f(x))^2$
    /// - For inequality constraints: $\sum (\max(0, f(x)))^2$
    pub fn total_violation_l2(&self) -> f64 {
        self.inner.total_violation_l2()
    }
}
