use anyhow::Result;
use pyo3::{
    exceptions::PyKeyError,
    exceptions::PyRuntimeError,
    prelude::*,
    types::{PyBytes, PyDict, PyTuple},
    Bound,
};
use std::collections::{BTreeSet, HashMap};

#[pyo3_stub_gen::derive::gen_stub_pyclass]
#[pyclass]
pub struct Solution {
    pub(crate) inner: ommx::Solution,
    pub(crate) annotations: HashMap<String, String>,
}

crate::annotations::impl_solution_annotations!(Solution, "org.ommx.v1.solution");

#[pyo3_stub_gen::derive::gen_stub_pymethods]
#[pymethods]
impl Solution {
    #[staticmethod]
    pub fn from_bytes(bytes: &Bound<PyBytes>) -> Result<Self> {
        Ok(Self {
            inner: ommx::Solution::from_bytes(bytes.as_bytes())?,
            annotations: HashMap::new(),
        })
    }

    pub fn to_bytes<'py>(&self, py: Python<'py>) -> Bound<'py, PyBytes> {
        PyBytes::new(py, &self.inner.to_bytes())
    }

    /// Get the objective function value
    #[getter]
    pub fn objective(&self) -> f64 {
        *self.inner.objective()
    }

    /// Get the solution state containing variable values
    #[getter]
    pub fn state(&self) -> crate::State {
        crate::State(self.inner.state())
    }

    /// Check if the solution is feasible
    #[getter]
    pub fn feasible(&self) -> bool {
        // The `feasible` means feasible in the unrelaxed problem
        self.inner.feasible()
    }

    /// Check if the solution is feasible in the relaxed problem
    #[getter]
    pub fn feasible_relaxed(&self) -> bool {
        self.inner.feasible_relaxed()
    }

    /// Check if the solution is feasible in the unrelaxed problem  
    #[getter]
    pub fn feasible_unrelaxed(&self) -> bool {
        self.inner.feasible()
    }

    // Get the optimization sense (minimize or maximize)
    #[getter]
    pub fn sense(&self) -> Result<crate::Sense> {
        let sense = (*self.inner.sense()).ok_or_else(|| {
            PyRuntimeError::new_err(
                "This property is available for ommx.v1.Solution generated by OMMX v2.0.0 or later."
            )
        })?;
        Ok(sense.into())
    }

    /// Get the optimality status
    #[getter]
    pub fn optimality(&self) -> crate::Optimality {
        self.inner.optimality.into()
    }

    /// Get the relaxation status
    #[getter]
    pub fn relaxation(&self) -> crate::Relaxation {
        self.inner.relaxation.into()
    }

    /// Set the optimality status
    #[setter]
    pub fn set_optimality(&mut self, optimality: crate::Optimality) {
        self.inner.optimality = optimality.into();
    }

    /// Set the relaxation status
    #[setter]
    pub fn set_relaxation(&mut self, relaxation: crate::Relaxation) {
        self.inner.relaxation = relaxation.into();
    }

    /// Get evaluated decision variables as a list sorted by ID
    #[getter]
    pub fn decision_variables(&self) -> Vec<crate::EvaluatedDecisionVariable> {
        // BTreeMap is already sorted by key
        self.inner
            .decision_variables()
            .values()
            .map(|dv| crate::EvaluatedDecisionVariable(dv.clone()))
            .collect()
    }

    /// Get evaluated constraints as a list sorted by ID
    #[getter]
    pub fn constraints(&self) -> Vec<crate::EvaluatedConstraint> {
        // BTreeMap is already sorted by key
        self.inner
            .evaluated_constraints()
            .values()
            .map(|ec| crate::EvaluatedConstraint(ec.clone()))
            .collect()
    }

    // Get evaluated named functions as a list sorted by ID
    pub fn named_functions(&self) -> Vec<crate::EvaluatedNamedFunction> {
        self.inner
            .evaluated_named_functions()
            .values()
            .map(|nf| crate::EvaluatedNamedFunction(nf.clone()))
            .collect()
    }

    #[getter]
    pub fn decision_variable_ids(&self) -> BTreeSet<u64> {
        self.inner
            .decision_variable_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    #[getter]
    pub fn constraint_ids(&self) -> BTreeSet<u64> {
        self.inner
            .constraint_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    /// Get all unique decision variable names in this solution
    #[getter]
    pub fn decision_variable_names(&self) -> BTreeSet<String> {
        self.inner.decision_variable_names()
    }

    #[getter]
    pub fn named_function_ids(&self) -> BTreeSet<u64> {
        self.inner
            .named_function_ids()
            .iter()
            .map(|id| id.into_inner())
            .collect()
    }

    /// Get all unique named function names in this solution
    #[getter]
    pub fn named_function_names(&self) -> BTreeSet<String> {
        self.inner.named_function_names()
    }

    /// Extract decision variables by name with subscripts as key (returns a Python dict)
    pub fn extract_decision_variables<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_decision_variables(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract all decision variables grouped by name (returns a Python dict)
    pub fn extract_all_decision_variables<'py>(
        &self,
        py: Python<'py>,
    ) -> Result<Bound<'py, PyDict>> {
        let result_dict = PyDict::new(py);
        for (name, variables) in self.inner.extract_all_decision_variables()? {
            let var_dict = PyDict::new(py);
            for (subscripts, value) in variables {
                let key_tuple = PyTuple::new(py, &subscripts)?;
                var_dict.set_item(key_tuple, value)?;
            }
            result_dict.set_item(name, var_dict)?;
        }
        Ok(result_dict)
    }

    /// Extract constraints by name with subscripts as key (returns a Python dict)
    pub fn extract_constraints<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_constraints(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract named functions by name with subscripts as key (returns a Python dict)
    pub fn extract_named_functions<'py>(
        &self,
        py: Python<'py>,
        name: &str,
    ) -> Result<Bound<'py, PyDict>> {
        let dict = PyDict::new(py);
        for (subscripts, value) in self.inner.extract_named_functions(name)? {
            let key_tuple = PyTuple::new(py, &subscripts)?;
            dict.set_item(key_tuple, value)?;
        }
        Ok(dict)
    }

    /// Extract all named functions grouped by name (returns a Python dict)
    pub fn extract_all_named_functions<'py>(&self, py: Python<'py>) -> Result<Bound<'py, PyDict>> {
        let result_dict = PyDict::new(py);
        for (name, functions) in self.inner.extract_all_named_functions()? {
            let func_dict = PyDict::new(py);
            for (subscripts, value) in functions {
                let key_tuple = PyTuple::new(py, &subscripts)?;
                func_dict.set_item(key_tuple, value)?;
            }
            result_dict.set_item(name, func_dict)?;
        }
        Ok(result_dict)
    }

    /// Set the dual variable value for a specific constraint by ID
    pub fn set_dual_variable(&mut self, constraint_id: u64, value: Option<f64>) -> PyResult<()> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .set_dual_variable(constraint_id, value)
            .map_err(|e| PyKeyError::new_err(e.to_string()))
    }

    /// Get a specific evaluated decision variable by ID
    pub fn get_decision_variable_by_id(
        &self,
        variable_id: u64,
    ) -> PyResult<crate::EvaluatedDecisionVariable> {
        let var_id = ommx::VariableID::from(variable_id);
        self.inner
            .decision_variables()
            .get(&var_id)
            .map(|dv| crate::EvaluatedDecisionVariable(dv.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!("Unknown decision variable ID: {variable_id}"))
            })
    }

    /// Get a specific evaluated constraint by ID
    pub fn get_constraint_by_id(&self, constraint_id: u64) -> PyResult<crate::EvaluatedConstraint> {
        let constraint_id = ommx::ConstraintID::from(constraint_id);
        self.inner
            .evaluated_constraints()
            .get(&constraint_id)
            .map(|ec| crate::EvaluatedConstraint(ec.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown constraint ID: {}",
                    constraint_id.into_inner()
                ))
            })
    }

    /// Get a specific evaluated named function by ID
    pub fn get_named_function_by_id(
        &self,
        named_function_id: u64,
    ) -> PyResult<crate::EvaluatedNamedFunction> {
        let named_function_id = ommx::NamedFunctionID::from(named_function_id);
        self.inner
            .evaluated_named_functions()
            .get(&named_function_id)
            .map(|nf| crate::EvaluatedNamedFunction(nf.clone()))
            .ok_or_else(|| {
                PyKeyError::new_err(format!(
                    "Unknown named function ID: {}",
                    named_function_id.into_inner()
                ))
            })
    }

    /// Calculate total constraint violation using L1 norm (sum of absolute violations)
    ///
    /// Returns the sum of violations across all constraints (including removed constraints):
    /// - For equality constraints: `Σ|f(x)|`
    /// - For inequality constraints: `Σmax(0, f(x))`
    pub fn total_violation_l1(&self) -> f64 {
        self.inner.total_violation_l1()
    }

    /// Calculate total constraint violation using L2 norm squared (sum of squared violations)
    ///
    /// Returns the sum of squared violations across all constraints (including removed constraints):
    /// - For equality constraints: `Σ(f(x))²`
    /// - For inequality constraints: `Σ(max(0, f(x)))²`
    pub fn total_violation_l2(&self) -> f64 {
        self.inner.total_violation_l2()
    }
}
