# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ommx/v1/named_function.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ommx.v1 import function_pb2 as ommx_dot_v1_dot_function__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1commx/v1/named_function.proto\x12\x07ommx.v1\x1a\x16ommx/v1/function.proto"\xce\x02\n\rNamedFunction\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12-\n\x08\x66unction\x18\x02 \x01(\x0b\x32\x11.ommx.v1.FunctionR\x08\x66unction\x12\x1e\n\nsubscripts\x18\x03 \x03(\x03R\nsubscripts\x12\x46\n\nparameters\x18\x04 \x03(\x0b\x32&.ommx.v1.NamedFunction.ParametersEntryR\nparameters\x12\x17\n\x04name\x18\x05 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n\x0b\x64\x65scription\x18\x06 \x01(\tH\x01R\x0b\x64\x65scription\x88\x01\x01\x1a=\n\x0fParametersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x07\n\x05_nameB\x0e\n\x0c_description"\x97\x03\n\x16\x45valuatedNamedFunction\x12\x0e\n\x02id\x18\x01 \x01(\x04R\x02id\x12\'\n\x0f\x65valuated_value\x18\x02 \x01(\x01R\x0e\x65valuatedValue\x12;\n\x1aused_decision_variable_ids\x18\x03 \x03(\x04R\x17usedDecisionVariableIds\x12\x1e\n\nsubscripts\x18\x04 \x03(\x03R\nsubscripts\x12O\n\nparameters\x18\x05 \x03(\x0b\x32/.ommx.v1.EvaluatedNamedFunction.ParametersEntryR\nparameters\x12\x17\n\x04name\x18\x06 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n\x0b\x64\x65scription\x18\x07 \x01(\tH\x01R\x0b\x64\x65scription\x88\x01\x01\x1a=\n\x0fParametersEntry\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value:\x02\x38\x01\x42\x07\n\x05_nameB\x0e\n\x0c_descriptionb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "ommx.v1.named_function_pb2", _globals
)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_NAMEDFUNCTION_PARAMETERSENTRY"]._loaded_options = None
    _globals["_NAMEDFUNCTION_PARAMETERSENTRY"]._serialized_options = b"8\001"
    _globals["_EVALUATEDNAMEDFUNCTION_PARAMETERSENTRY"]._loaded_options = None
    _globals["_EVALUATEDNAMEDFUNCTION_PARAMETERSENTRY"]._serialized_options = b"8\001"
    _globals["_NAMEDFUNCTION"]._serialized_start = 66
    _globals["_NAMEDFUNCTION"]._serialized_end = 400
    _globals["_NAMEDFUNCTION_PARAMETERSENTRY"]._serialized_start = 314
    _globals["_NAMEDFUNCTION_PARAMETERSENTRY"]._serialized_end = 375
    _globals["_EVALUATEDNAMEDFUNCTION"]._serialized_start = 403
    _globals["_EVALUATEDNAMEDFUNCTION"]._serialized_end = 810
    _globals["_EVALUATEDNAMEDFUNCTION_PARAMETERSENTRY"]._serialized_start = 314
    _globals["_EVALUATEDNAMEDFUNCTION_PARAMETERSENTRY"]._serialized_end = 375
# @@protoc_insertion_point(module_scope)
