# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ommx/v1/solution.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ommx.v1 import constraint_pb2 as ommx_dot_v1_dot_constraint__pb2
from ommx.v1 import decision_variables_pb2 as ommx_dot_v1_dot_decision__variables__pb2
from ommx.v1 import instance_pb2 as ommx_dot_v1_dot_instance__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x16ommx/v1/solution.proto\x12\x07ommx.v1\x1a\x18ommx/v1/constraint.proto\x1a ommx/v1/decision_variables.proto\x1a\x16ommx/v1/instance.proto"z\n\x05State\x12\x35\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x1b.ommx.v1.State.EntriesEntryR\x07\x65ntries\x1a:\n\x0c\x45ntriesEntry\x12\x10\n\x03key\x18\x01 \x01(\x04R\x03key\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value:\x02\x38\x01"\x98\x04\n\x08Solution\x12$\n\x05state\x18\x01 \x01(\x0b\x32\x0e.ommx.v1.StateR\x05state\x12\x1c\n\tobjective\x18\x02 \x01(\x01R\tobjective\x12H\n\x12\x64\x65\x63ision_variables\x18\x03 \x03(\x0b\x32\x19.ommx.v1.DecisionVariableR\x11\x64\x65\x63isionVariables\x12Q\n\x15\x65valuated_constraints\x18\x04 \x03(\x0b\x32\x1c.ommx.v1.EvaluatedConstraintR\x14\x65valuatedConstraints\x12\x1a\n\x08\x66\x65\x61sible\x18\x05 \x01(\x08R\x08\x66\x65\x61sible\x12.\n\x10\x66\x65\x61sible_relaxed\x18\t \x01(\x08H\x00R\x0f\x66\x65\x61sibleRelaxed\x88\x01\x01\x12\x31\n\x12\x66\x65\x61sible_unrelaxed\x18\x08 \x01(\x08\x42\x02\x18\x01R\x11\x66\x65\x61sibleUnrelaxed\x12\x33\n\noptimality\x18\x06 \x01(\x0e\x32\x13.ommx.v1.OptimalityR\noptimality\x12\x33\n\nrelaxation\x18\x07 \x01(\x0e\x32\x13.ommx.v1.RelaxationR\nrelaxation\x12-\n\x05sense\x18\n \x01(\x0e\x32\x17.ommx.v1.Instance.SenseR\x05senseB\x13\n\x11_feasible_relaxed"\x0c\n\nInfeasible"\x0b\n\tUnbounded"\xc6\x01\n\x06Result\x12\x16\n\x05\x65rror\x18\x01 \x01(\tH\x00R\x05\x65rror\x12/\n\x08solution\x18\x02 \x01(\x0b\x32\x11.ommx.v1.SolutionH\x00R\x08solution\x12\x35\n\ninfeasible\x18\x03 \x01(\x0b\x32\x13.ommx.v1.InfeasibleH\x00R\ninfeasible\x12\x32\n\tunbounded\x18\x04 \x01(\x0b\x32\x12.ommx.v1.UnboundedH\x00R\tunboundedB\x08\n\x06result*\\\n\nOptimality\x12\x1a\n\x16OPTIMALITY_UNSPECIFIED\x10\x00\x12\x16\n\x12OPTIMALITY_OPTIMAL\x10\x01\x12\x1a\n\x16OPTIMALITY_NOT_OPTIMAL\x10\x02*C\n\nRelaxation\x12\x1a\n\x16RELAXATION_UNSPECIFIED\x10\x00\x12\x19\n\x15RELAXATION_LP_RELAXED\x10\x01\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ommx.v1.solution_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_STATE_ENTRIESENTRY"]._loaded_options = None
    _globals["_STATE_ENTRIESENTRY"]._serialized_options = b"8\001"
    _globals["_SOLUTION"].fields_by_name["feasible_unrelaxed"]._loaded_options = None
    _globals["_SOLUTION"].fields_by_name[
        "feasible_unrelaxed"
    ]._serialized_options = b"\030\001"
    _globals["_OPTIMALITY"]._serialized_start = 1010
    _globals["_OPTIMALITY"]._serialized_end = 1102
    _globals["_RELAXATION"]._serialized_start = 1104
    _globals["_RELAXATION"]._serialized_end = 1171
    _globals["_STATE"]._serialized_start = 119
    _globals["_STATE"]._serialized_end = 241
    _globals["_STATE_ENTRIESENTRY"]._serialized_start = 183
    _globals["_STATE_ENTRIESENTRY"]._serialized_end = 241
    _globals["_SOLUTION"]._serialized_start = 244
    _globals["_SOLUTION"]._serialized_end = 780
    _globals["_INFEASIBLE"]._serialized_start = 782
    _globals["_INFEASIBLE"]._serialized_end = 794
    _globals["_UNBOUNDED"]._serialized_start = 796
    _globals["_UNBOUNDED"]._serialized_end = 807
    _globals["_RESULT"]._serialized_start = 810
    _globals["_RESULT"]._serialized_end = 1008
# @@protoc_insertion_point(module_scope)
