# pyright: reportIncompatibleVariableOverride=false
"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class SOS1(google.protobuf.message.Message):
    """A message representing a [Spcial Ordered Set constraint of Type 1](https://en.wikipedia.org/wiki/Special_ordered_set#Types) (SOS1).
    SOS1 constraint on non-negative variables x_1, ..., x_n
    requires that at most one of x_i can be non-zero.
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    BINARY_CONSTRAINT_ID_FIELD_NUMBER: builtins.int
    BIG_M_CONSTRAINT_IDS_FIELD_NUMBER: builtins.int
    DECISION_VARIABLES_FIELD_NUMBER: builtins.int
    binary_constraint_id: builtins.int
    """The ID of the SOS1 constraint on binary variables."""
    @property
    def big_m_constraint_ids(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The IDs of the big-M constraint on non-binary variables."""

    @property
    def decision_variables(
        self,
    ) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """The list of ids of decision variables that are constrained to be one-hot."""

    def __init__(
        self,
        *,
        binary_constraint_id: builtins.int = ...,
        big_m_constraint_ids: collections.abc.Iterable[builtins.int] | None = ...,
        decision_variables: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing.Literal[
            "big_m_constraint_ids",
            b"big_m_constraint_ids",
            "binary_constraint_id",
            b"binary_constraint_id",
            "decision_variables",
            b"decision_variables",
        ],
    ) -> None: ...

global___SOS1 = SOS1
