# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ommx/v1/sos1.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x12ommx/v1/sos1.proto\x12\x07ommx.v1"\x98\x01\n\x04SOS1\x12\x30\n\x14\x62inary_constraint_id\x18\x01 \x01(\x04R\x12\x62inaryConstraintId\x12/\n\x14\x62ig_m_constraint_ids\x18\x02 \x03(\x04R\x11\x62igMConstraintIds\x12-\n\x12\x64\x65\x63ision_variables\x18\x03 \x03(\x04R\x11\x64\x65\x63isionVariablesb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ommx.v1.sos1_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_SOS1"]._serialized_start = 32
    _globals["_SOS1"]._serialized_end = 184
# @@protoc_insertion_point(module_scope)
