# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: "Build the book in docs/en"
    cmds:
      - uv run jupyter book build --html --ci .

  start:
    desc: "Start development server for docs/en"
    cmds:
      - uv run jupyter book start .

  test:
    desc: "Test each notebook in the book"
    cmds:
      - uv run pytest --nbval-lax tutorial/*.md user_guide/*.md

  open:
    desc: "Open the book in docs/en"
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/_build/html/index.html

  default:
    desc: "Build and open the book in docs/en"
    cmds:
      - task: build
      - task: open
