# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: "Build the book in docs/en"
    cmds:
      - jupyter-book build .

  open:
    desc: "Open the book in docs/en"
    cmds:
      - python -m webbrowser file:///$(pwd)/_build/html/index.html

  watch:
    desc: "Watch the book in docs/en"
    cmds:
      - fswatch -o $(find . -name '*.ipynb' -or -name '*.md') | xargs -n1 -I{} jupyter-book build .

  default:
    desc: "Build and open the book in docs/en"
    cmds:
      - task: build
      - task: open
