# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: "Build the Sphinx documentation in docs/en"
    cmds:
      - uv run sphinx-build -b html . _build/html

  open:
    desc: "Open the documentation in docs/en"
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/_build/html/index.html

  default:
    desc: "Build and open the documentation in docs/en"
    cmds:
      - task: build
      - task: open
