class Descriptor:
    @property
    def digest(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def annotations(self) -> dict[str, str]: ...

class Artifact:
    @staticmethod
    def from_oci_archive(path: str) -> Artifact: ...
    @property
    def instance_descriptors(self) -> list[Descriptor]: ...

def evaluate_function(function: bytes, state: bytes) -> tuple[float, set[int]]: ...
