class InstanceDescriptor:
    def digest(self) -> str: ...
    def size(self) -> int: ...
    def annotations(self) -> dict[str, str]: ...

class Artifact:
    @staticmethod
    def from_oci_archive(path: str) -> Artifact: ...
    def get_instance_descriptors(self) -> list[InstanceDescriptor]: ...
