# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests for OMMX Python SDK
    cmds:
      - task: pytest
      - task: pyright
      - task: lint

  test-ci:
    desc: Run tests for OMMX Python SDK (CI mode; without pyright)
    cmds:
      - task: pytest

  pytest:
    desc: Run pytest for OMMX Python SDK
    cmds:
      - uv run pytest -vv --doctest-modules python/ommx-tests
    dir: ../.. # Doctest users ${repo_root}/data/

  pytest-doctest:
    desc: Run only doctest modules
    cmds:
      - uv run pytest -vv --doctest-modules python/ommx-tests/tests/test_doctests.py
    dir: ../.. # Doctest users ${repo_root}/data/

  pytest-bench:
    desc: Run only benchmark tests
    cmds:
      - uv run pytest -vv python/ommx-tests/tests/test_bench_*.py
    dir: ../.. # Doctest users ${repo_root}/data/

  pytest-unit:
    desc: Run unit tests (excluding doctest and bench)
    cmds:
      - uv run pytest -vv python/ommx-tests/tests --ignore=python/ommx-tests/tests/test_doctests.py --ignore-glob=python/ommx-tests/tests/test_bench_*.py
    dir: ../.. # Doctest users ${repo_root}/data/

  pyright:
    desc: Type check OMMX Python SDK
    cmds:
      - uv run pyright python/ommx python/ommx-tests
    dir: ../..

  lint:
    desc: Lint by ruff check
    cmds:
      - uv run ruff check python/ommx python/ommx-tests
    dir: ../..

  bench:
    desc: Run benchmarks for OMMX Python SDK
    cmds:
      - uv run pytest python/ommx-tests --codspeed
    dir: ../.. # Doctest users ${repo_root}/data/
