# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

#
# Some tasks have to run in `../..` since they uses `${repo_root}/data`
#

version: "3"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests for OMMX Python SDK
    cmds:
      - task: pyright
      - task: lint
      - task: pytest

  pytest:
    desc: Run pytest for OMMX Python SDK
    cmds:
      - task: pytest-unit
      - task: pytest-doctest
      - task: pytest-bench

  pytest-doctest:
    desc: Run only doctest modules
    cmds:
      - uv run pytest -vv --doctest-modules python/ommx-tests/tests/test_doctests.py
    dir: ../..

  pytest-bench:
    desc: Run only benchmark tests
    cmds:
      - uv run pytest -vv python/ommx-tests/tests/test_bench_*.py
    dir: ../..

  pytest-unit:
    desc: Run unit tests (excluding doctest and bench)
    cmds:
      - uv run pytest -vv python/ommx-tests/tests --ignore=python/ommx-tests/tests/test_doctests.py --ignore-glob=python/ommx-tests/tests/test_bench_*.py
    dir: ../..

  pyright:
    desc: Type check OMMX Python SDK
    cmds:
      - uv run pyright python/ommx python/ommx-tests
    dir: ../..

  lint:
    desc: Lint by ruff check
    cmds:
      - uv run ruff check python/ommx python/ommx-tests
    dir: ../..

  bench:
    desc: Run benchmarks for OMMX Python SDK
    cmds:
      - uv run pytest python/ommx-tests --codspeed
    dir: ../..
