# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: "Build the book in docs/ja"
    cmds:
      - uv run jupyter-book build .

  pyright:
    desc: "Run type checks on the book notebooks"
    cmds:
      - uv run nbqa pyright tutorial/*.ipynb user_guide/*.ipynb

  test:
    desc: "Test each notebook in the book"
    cmds:
      - uv run pytest --nbval-lax tutorial/*.ipynb user_guide/*.ipynb

  open:
    desc: "Open the book in docs/ja"
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/_build/html/index.html

  watch:
    desc: "Watch the book in docs/ja"
    cmds:
      - fswatch -o $(find . -name '*.ipynb' -or -name '*.md') | xargs -n1 -I{} uv run jupyter-book build .

  default:
    desc: "Build and open the book in docs/ja"
    cmds:
      - task: build
      - task: open
