// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ommx/v1/function.proto
// Protobuf C++ Version: 5.26.1

#include "ommx/v1/function.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace ommx {
namespace v1 {

inline constexpr Function::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : function_{},
        _cached_size_{0},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR Function::Function(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct FunctionDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FunctionDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FunctionDefaultTypeInternal() {}
  union {
    Function _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FunctionDefaultTypeInternal _Function_default_instance_;
}  // namespace v1
}  // namespace ommx
static ::_pb::Metadata file_level_metadata_ommx_2fv1_2ffunction_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_ommx_2fv1_2ffunction_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_ommx_2fv1_2ffunction_2eproto = nullptr;
const ::uint32_t
    TableStruct_ommx_2fv1_2ffunction_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::ommx::v1::Function, _internal_metadata_),
        ~0u,  // no _extensions_
        PROTOBUF_FIELD_OFFSET(::ommx::v1::Function, _impl_._oneof_case_[0]),
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        ::_pbi::kInvalidFieldOffsetTag,
        PROTOBUF_FIELD_OFFSET(::ommx::v1::Function, _impl_.function_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::ommx::v1::Function)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::ommx::v1::_Function_default_instance_._instance,
};
const char descriptor_table_protodef_ommx_2fv1_2ffunction_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026ommx/v1/function.proto\022\007ommx.v1\032\024ommx/"
    "v1/linear.proto\032\030ommx/v1/polynomial.prot"
    "o\032\027ommx/v1/quadratic.proto\"\312\001\n\010Function\022"
    "\034\n\010constant\030\001 \001(\001H\000R\010constant\022)\n\006linear\030"
    "\002 \001(\0132\017.ommx.v1.LinearH\000R\006linear\0222\n\tquad"
    "ratic\030\003 \001(\0132\022.ommx.v1.QuadraticH\000R\tquadr"
    "atic\0225\n\npolynomial\030\004 \001(\0132\023.ommx.v1.Polyn"
    "omialH\000R\npolynomialB\n\n\010functionBY\n\013com.o"
    "mmx.v1B\rFunctionProtoP\001\242\002\003OXX\252\002\007Ommx.V1\312"
    "\002\007Ommx\\V1\342\002\023Ommx\\V1\\GPBMetadata\352\002\010Ommx::"
    "V1b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_ommx_2fv1_2ffunction_2eproto_deps[3] =
    {
        &::descriptor_table_ommx_2fv1_2flinear_2eproto,
        &::descriptor_table_ommx_2fv1_2fpolynomial_2eproto,
        &::descriptor_table_ommx_2fv1_2fquadratic_2eproto,
};
static ::absl::once_flag descriptor_table_ommx_2fv1_2ffunction_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ommx_2fv1_2ffunction_2eproto = {
    false,
    false,
    410,
    descriptor_table_protodef_ommx_2fv1_2ffunction_2eproto,
    "ommx/v1/function.proto",
    &descriptor_table_ommx_2fv1_2ffunction_2eproto_once,
    descriptor_table_ommx_2fv1_2ffunction_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_ommx_2fv1_2ffunction_2eproto::offsets,
    file_level_metadata_ommx_2fv1_2ffunction_2eproto,
    file_level_enum_descriptors_ommx_2fv1_2ffunction_2eproto,
    file_level_service_descriptors_ommx_2fv1_2ffunction_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ommx_2fv1_2ffunction_2eproto_getter() {
  return &descriptor_table_ommx_2fv1_2ffunction_2eproto;
}
namespace ommx {
namespace v1 {
// ===================================================================

class Function::_Internal {
 public:
  static constexpr ::int32_t kOneofCaseOffset =
    PROTOBUF_FIELD_OFFSET(::ommx::v1::Function, _impl_._oneof_case_);
};

void Function::set_allocated_linear(::ommx::v1::Linear* linear) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_function();
  if (linear) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(linear)->GetArena();
    if (message_arena != submessage_arena) {
      linear = ::google::protobuf::internal::GetOwnedMessage(message_arena, linear, submessage_arena);
    }
    set_has_linear();
    _impl_.function_.linear_ = linear;
  }
  // @@protoc_insertion_point(field_set_allocated:ommx.v1.Function.linear)
}
void Function::clear_linear() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (function_case() == kLinear) {
    if (GetArena() == nullptr) {
      delete _impl_.function_.linear_;
    }
    clear_has_function();
  }
}
void Function::set_allocated_quadratic(::ommx::v1::Quadratic* quadratic) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_function();
  if (quadratic) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(quadratic)->GetArena();
    if (message_arena != submessage_arena) {
      quadratic = ::google::protobuf::internal::GetOwnedMessage(message_arena, quadratic, submessage_arena);
    }
    set_has_quadratic();
    _impl_.function_.quadratic_ = quadratic;
  }
  // @@protoc_insertion_point(field_set_allocated:ommx.v1.Function.quadratic)
}
void Function::clear_quadratic() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (function_case() == kQuadratic) {
    if (GetArena() == nullptr) {
      delete _impl_.function_.quadratic_;
    }
    clear_has_function();
  }
}
void Function::set_allocated_polynomial(::ommx::v1::Polynomial* polynomial) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_function();
  if (polynomial) {
    ::google::protobuf::Arena* submessage_arena = reinterpret_cast<::google::protobuf::MessageLite*>(polynomial)->GetArena();
    if (message_arena != submessage_arena) {
      polynomial = ::google::protobuf::internal::GetOwnedMessage(message_arena, polynomial, submessage_arena);
    }
    set_has_polynomial();
    _impl_.function_.polynomial_ = polynomial;
  }
  // @@protoc_insertion_point(field_set_allocated:ommx.v1.Function.polynomial)
}
void Function::clear_polynomial() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (function_case() == kPolynomial) {
    if (GetArena() == nullptr) {
      delete _impl_.function_.polynomial_;
    }
    clear_has_function();
  }
}
Function::Function(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:ommx.v1.Function)
}
inline PROTOBUF_NDEBUG_INLINE Function::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : function_{},
        _cached_size_{0},
        _oneof_case_{from._oneof_case_[0]} {}

Function::Function(
    ::google::protobuf::Arena* arena,
    const Function& from)
    : ::google::protobuf::Message(arena) {
  Function* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  switch (function_case()) {
    case FUNCTION_NOT_SET:
      break;
      case kConstant:
        _impl_.function_.constant_ = from._impl_.function_.constant_;
        break;
      case kLinear:
        _impl_.function_.linear_ = ::google::protobuf::Message::CopyConstruct<::ommx::v1::Linear>(arena, *from._impl_.function_.linear_);
        break;
      case kQuadratic:
        _impl_.function_.quadratic_ = ::google::protobuf::Message::CopyConstruct<::ommx::v1::Quadratic>(arena, *from._impl_.function_.quadratic_);
        break;
      case kPolynomial:
        _impl_.function_.polynomial_ = ::google::protobuf::Message::CopyConstruct<::ommx::v1::Polynomial>(arena, *from._impl_.function_.polynomial_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:ommx.v1.Function)
}
inline PROTOBUF_NDEBUG_INLINE Function::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : function_{},
        _cached_size_{0},
        _oneof_case_{} {}

inline void Function::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
Function::~Function() {
  // @@protoc_insertion_point(destructor:ommx.v1.Function)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Function::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  if (has_function()) {
    clear_function();
  }
  _impl_.~Impl_();
}

void Function::clear_function() {
// @@protoc_insertion_point(one_of_clear_start:ommx.v1.Function)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  switch (function_case()) {
    case kConstant: {
      // No need to clear
      break;
    }
    case kLinear: {
      if (GetArena() == nullptr) {
        delete _impl_.function_.linear_;
      }
      break;
    }
    case kQuadratic: {
      if (GetArena() == nullptr) {
        delete _impl_.function_.quadratic_;
      }
      break;
    }
    case kPolynomial: {
      if (GetArena() == nullptr) {
        delete _impl_.function_.polynomial_;
      }
      break;
    }
    case FUNCTION_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = FUNCTION_NOT_SET;
}


const ::google::protobuf::MessageLite::ClassData*
Function::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              nullptr,  // OnDemandRegisterArenaDtor
              PROTOBUF_FIELD_OFFSET(Function, _impl_._cached_size_),
              false,
          },
          &Function::MergeImpl,
          &Function::kDescriptorMethods,
      };
  return &_data_;
}
PROTOBUF_NOINLINE void Function::Clear() {
// @@protoc_insertion_point(message_clear_start:ommx.v1.Function)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_function();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Function::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 3, 0, 2> Function::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Function_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::ommx::v1::Function>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // double constant = 1 [json_name = "constant"];
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.function_.constant_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kDouble)},
    // .ommx.v1.Linear linear = 2 [json_name = "linear"];
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.function_.linear_), _Internal::kOneofCaseOffset + 0, 0,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ommx.v1.Quadratic quadratic = 3 [json_name = "quadratic"];
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.function_.quadratic_), _Internal::kOneofCaseOffset + 0, 1,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .ommx.v1.Polynomial polynomial = 4 [json_name = "polynomial"];
    {PROTOBUF_FIELD_OFFSET(Function, _impl_.function_.polynomial_), _Internal::kOneofCaseOffset + 0, 2,
    (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::ommx::v1::Linear>()},
    {::_pbi::TcParser::GetTable<::ommx::v1::Quadratic>()},
    {::_pbi::TcParser::GetTable<::ommx::v1::Polynomial>()},
  }}, {{
  }},
};

::uint8_t* Function::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ommx.v1.Function)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  switch (function_case()) {
    case kConstant: {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteDoubleToArray(
          1, this->_internal_constant(), target);
      break;
    }
    case kLinear: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *_impl_.function_.linear_, _impl_.function_.linear_->GetCachedSize(), target, stream);
      break;
    }
    case kQuadratic: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *_impl_.function_.quadratic_, _impl_.function_.quadratic_->GetCachedSize(), target, stream);
      break;
    }
    case kPolynomial: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *_impl_.function_.polynomial_, _impl_.function_.polynomial_->GetCachedSize(), target, stream);
      break;
    }
    default:
      break;
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ommx.v1.Function)
  return target;
}

::size_t Function::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ommx.v1.Function)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  switch (function_case()) {
    // double constant = 1 [json_name = "constant"];
    case kConstant: {
      total_size += 9;
      break;
    }
    // .ommx.v1.Linear linear = 2 [json_name = "linear"];
    case kLinear: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.function_.linear_);
      break;
    }
    // .ommx.v1.Quadratic quadratic = 3 [json_name = "quadratic"];
    case kQuadratic: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.function_.quadratic_);
      break;
    }
    // .ommx.v1.Polynomial polynomial = 4 [json_name = "polynomial"];
    case kPolynomial: {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::MessageSize(*_impl_.function_.polynomial_);
      break;
    }
    case FUNCTION_NOT_SET: {
      break;
    }
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Function::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Function*>(&to_msg);
  auto& from = static_cast<const Function&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:ommx.v1.Function)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (const uint32_t oneof_from_case = from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_function();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kConstant: {
        _this->_impl_.function_.constant_ = from._impl_.function_.constant_;
        break;
      }
      case kLinear: {
        if (oneof_needs_init) {
          _this->_impl_.function_.linear_ =
              ::google::protobuf::Message::CopyConstruct<::ommx::v1::Linear>(arena, *from._impl_.function_.linear_);
        } else {
          _this->_impl_.function_.linear_->MergeFrom(from._internal_linear());
        }
        break;
      }
      case kQuadratic: {
        if (oneof_needs_init) {
          _this->_impl_.function_.quadratic_ =
              ::google::protobuf::Message::CopyConstruct<::ommx::v1::Quadratic>(arena, *from._impl_.function_.quadratic_);
        } else {
          _this->_impl_.function_.quadratic_->MergeFrom(from._internal_quadratic());
        }
        break;
      }
      case kPolynomial: {
        if (oneof_needs_init) {
          _this->_impl_.function_.polynomial_ =
              ::google::protobuf::Message::CopyConstruct<::ommx::v1::Polynomial>(arena, *from._impl_.function_.polynomial_);
        } else {
          _this->_impl_.function_.polynomial_->MergeFrom(from._internal_polynomial());
        }
        break;
      }
      case FUNCTION_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Function::CopyFrom(const Function& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ommx.v1.Function)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Function::IsInitialized() const {
  return true;
}

void Function::InternalSwap(Function* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_.function_, other->_impl_.function_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata Function::GetMetadata() const {
  return ::_pbi::AssignDescriptors(&descriptor_table_ommx_2fv1_2ffunction_2eproto_getter,
                                   &descriptor_table_ommx_2fv1_2ffunction_2eproto_once,
                                   file_level_metadata_ommx_2fv1_2ffunction_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace ommx
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::std::false_type _static_init_ PROTOBUF_UNUSED =
    (::_pbi::AddDescriptors(&descriptor_table_ommx_2fv1_2ffunction_2eproto),
     ::std::false_type{});
#include "google/protobuf/port_undef.inc"
