[package]
name = "protogen"
version = "0.1.0"
edition = "2021"

# This crate is only for developing in this repository
publish = false

[dependencies]
anyhow.workspace = true
colored.workspace = true
glob.workspace = true
prost-build.workspace = true
