# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  doc:
    desc: Generate and Open documentation for Rust SDK
    cmds:
      - cargo doc --no-deps -p ommx {{.CLI_ARGS}}

  test:
    desc: Run tests for Rust SDK
    cmds:
      - cargo test -p ommx {{.CLI_ARGS}}

  check:
    desc: Run check for Rust SDK
    cmds:
      - cargo check -p ommx {{.CLI_ARGS}}

  clippy:
    desc: Run clippy for Rust SDK
    cmds:
      - cargo clippy {{.CLI_ARGS}}

  set-version:
    desc: Set version for Rust SDK
    cmds:
      - cargo set-version {{.CLI_ARGS}}

  format:
    desc: Format Rust code
    cmds:
      - cargo fmt --all

  insta:
    desc: Run insta snapshot tests (use --accept to accept changes)
    cmds:
      - cargo insta test {{.CLI_ARGS}}

  insta:review:
    desc: Review insta snapshot changes
    cmds:
      - cargo insta review

  insta:accept:
    desc: Run insta tests and accept all changes
    cmds:
      - cargo insta test --accept
