name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

inputs:
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.8"

runs:
  using: "composite"
  steps:
    - name: Setup protobuf compiler
      uses: arduino/setup-protoc@v3
      with:
        version: "26.1"
        repo-token: ${{ github.token }}

    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Setup caching for Rust
      uses: Swatinem/rust-cache@v2

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Setup Python tools
      shell: bash
      run: |
        pip install "ruff >= 0.7.0, < 0.8.0"
        pip install pytest-github-actions-annotate-failures
