name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

runs:
  using: "composite"
  steps:
    - name: Setup protobuf compiler
      uses: arduino/setup-protoc@v3
      with:
        version: "26.1"
        repo-token: ${{ github.token }}

    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Setup caching for Rust
      uses: Swatinem/rust-cache@v2
