name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

inputs:
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.10"
  setup-wasm:
    description: "Setup WASM toolchain (Rust nightly, Emscripten, Node.js)"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    # Though buf does not need protoc due to remote plugin support, it is still required for Rust/prost
    - name: Setup protobuf compiler
      uses: arduino/setup-protoc@v3
      with:
        version: "26.1"
        repo-token: ${{ github.token }}

    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Setup Rust (stable)
      if: inputs.setup-wasm == 'false'
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Setup Rust (nightly for WASM)
      if: inputs.setup-wasm == 'true'
      uses: dtolnay/rust-toolchain@nightly
      with:
        targets: wasm32-unknown-emscripten

    - name: Setup Emscripten
      if: inputs.setup-wasm == 'true'
      uses: mymindstorm/setup-emsdk@v14

    - name: Setup Node.js
      if: inputs.setup-wasm == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Setup caching for Rust
      uses: Swatinem/rust-cache@v2

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Fix Python Version
      shell: bash
      run: |
        echo "cpython@${{inputs.python-version}}" > .python-version
    - name: Setup Python Tools
      shell: bash
      run: |
        uv tool install "ruff >= 0.9.0, < 0.10.0"
        uv tool install "twine >= 6.0.0, < 7.0.0"
