name: "Setup Test Environment"
description: "Setup common environment for testing jobs"

inputs:
  python-version:
    description: "Python version to setup"
    required: true
    default: "3.9"

runs:
  using: "composite"
  steps:
    # Though buf does not need protoc due to remote plugin support, it is still required for Rust/prost
    - name: Setup protobuf compiler
      uses: arduino/setup-protoc@v3
      with:
        version: "26.1"
        repo-token: ${{ github.token }}

    - name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        github_token: ${{ github.token }}

    - name: Install Task
      uses: arduino/setup-task@v2
      with:
        version: 3.x
        repo-token: ${{ github.token }}

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy

    - name: Setup caching for Rust
      uses: Swatinem/rust-cache@v2

    - name: Setup Python
      # TODO: Bump to v* type version, once 9e62be8 is inclued in release
      uses: actions/setup-python@9e62be81b28222addecf85e47571213eb7680449
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        sync: false
    
    - name: Setup Python Tools
      shell: bash
      run: |
        uv tool install "ruff >= 0.9.0, < 0.10.0"
        uv tool install "twine >= 6.0.0, < 7.0.0"
        uv tool install build
