# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    desc: Generate code from Protobuf definitions
    cmds:
      - task: rust

  rust:
    desc: Generate Rust code from Protobuf definitions
    cmds:
      - cargo run --bin protogen

  doc:
    desc: Generate documentation from Protobuf definitions
    cmds:
      - buf generate --template buf.gen.docs.yaml

  format:
    desc: Format all protobuf files
    cmds:
    - buf format -w .
