# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  default:
    cmds:
      - task: test

  test:
    desc: Run tests for OMMX OpenJij Adapter
    cmds:
      - uv run pytest -vv --doctest-modules
      - uv run pyright
      - task: lint

  lint:
    desc: Lint by ruff check
    cmds:
      - uv run ruff check
