# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    cmds:
      - uv run sphinx-build -b html . _build/html

  open:
    cmds:
      - uv run python -m webbrowser file:///$(pwd)/_build/html/autoapi/index.html
