name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request: # FIXME
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup protobuf compiler
        uses: arduino/setup-protoc@v1
        with:
          version: 3.20.1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v5
        with:
          go-version: ">=1.17"

      - name: Print go version
        run: go version

      - name: Setup protoc-gen-doc plugin
        run: |
          go install github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc@latest

      - name: Generate API docs
        run: |
          mkdir -p ./doc
          protoc --proto_path=./protobuf --doc_out=./doc --doc_opt=html,protobuf.html protobuf/*.proto

      - name: Upload html
        uses: actions/upload-artifact@v4
        with:
          name: doc-protobuf
          path: ./doc
          retention-days: 30

  deploy:
    needs: [protobuf]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Download html
        uses: actions/download-artifact@v4
        with:
          pattern: doc-*
          merge-multiple: true

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
