name: Publish OMMX-PythonMIP-Adapter on PyPI

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build Python Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      
      - name: Build
        run: |
          python -m pip install --upgrade pip build
          python -m build --sdist --outdir ./dist .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./dist/
          retention-days: 30

  publish:
    if: ${{ github.event_name != 'workflow_dispatch' }}
    name: Publish Python Package
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: ./dist

      - name: Upload to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
