name: Python

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  protogen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Install dependencies
        run: pip install "python/ommx/[dev]"

      - name: Regenerate python bindings
        run: task protogen_python

      - name: Check updated
        run: |
          git add -N python/ommx/ommx/  # To check newly generated files
          git diff --exit-code

  stub-gen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Regenerate stub file
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin stub_gen --features=stub_gen

      - name: Check updated
        run: |
          git diff --exit-code python/ommx/ommx/_ommx_rust.pyi

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install ommx
        run: |
          pip install -v -e 'python/ommx/[dev]'

      - name: Test ommx
        if: always()
        run: |
          pytest -vv --doctest-modules python/ommx

      # FIXME: Python-MIP does not support Python 3.12
      - name: Install ommx-python-mip-adapter
        if: ${{ matrix.python-version != '3.12' }}
        run: |
          pip install -v -e 'python/ommx-python-mip-adapter/[dev]'

      - name: Test ommx-python-mip-adapter
        if: ${{ matrix.python-version != '3.12' }}
        run: |
          pytest -vv --doctest-modules python/ommx-python-mip-adapter/
          markdown-code-runner ./python/ommx-python-mip-adapter/README.md

      - name: Run notebooks
        if: ${{ github.actor != 'dependabot[bot]' && matrix.python-version != '3.12' }}
        run: |
          jupyter nbconvert --to notebook --execute notebooks/*.ipynb
        env:
          OMMX_BASIC_AUTH_DOMAIN: ghcr.io
          OMMX_BASIC_AUTH_USERNAME: ${{ github.actor }}
          OMMX_BASIC_AUTH_PASSWORD: ${{ github.token }}

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Format
        run: |
          ruff format --check python

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Lint
        run: |
          ruff check python

      - name: Type check
        run: |
          pyright python
