name: Release Rust SDK

on:
  push:
    tags:
      - rust-*
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for OIDC token exchange
    steps:
      - uses: actions/checkout@v4
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish -p ommx
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

  next_version:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo-edit
        run: cargo install cargo-edit

      - name: Bump version
        run: |
          cargo set-version --bump patch
          echo "NEW_VERSION=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          title: "Start developing ${{ env.NEW_VERSION }}"
          branch: "rust-version-update/${{ env.NEW_VERSION }}"
          base: "main"
