name: Rust

on:
  pull_request:
  workflow_dispatch:

jobs:
  doc-check:
    defaults:
      run:
        working-directory: ./rust

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check warnings in documents
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --manifest-path=rust/Cargo.toml
        env:
          RUSTDOCFLAGS: -D warnings

  format:
    defaults:
      run:
        working-directory: ./rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path=rust/Cargo.toml --all -- --check

  clippy:
    defaults:
      run:
        working-directory: ./rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check with clippy
        uses: actions-rs/clippy-check@v1
        with:
          args: --manifest-path=rust/Cargo.toml --all-features -- -D warnings
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    defaults:
      run:
        working-directory: ./rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=rust/Cargo.toml

  protogen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Setup protobuf compiler
        uses: arduino/setup-protoc@v1
        with:
          version: 3.20.1

      - name: Regenerate Rust codes from proto files
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin=protogen --manifest-path=rust/Cargo.toml

      - name: Check updated
        run: |
          git diff --exit-code
