name: Update LLMs.md

on:
  push:
    branches:
      - main
    paths:
      - "python/generate_llms_md.py"
      - "LLMs.md"
      - "docs/en/**/*.ipynb"
      - "docs/en/_toc.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  detect-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Generate LLMs.md
        run: |
          # Run the script to generate a new LLMs.md file
          uv run python/generate_llms_md.py

          # Check if there are differences
          if ! git diff --exit-code LLMs.md; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.TOKEN_PROVIDER_OMMX_APP_ID }}
          private-key: ${{ secrets.TOKEN_PROVIDER_OMMX_PRIVATE_KEY }}

      - name: Create Pull Request if changes detected
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "Update LLMs.md"
          body: "Automatically generated update for LLMs.md based on notebook changes."
          branch: "auto-update/llms-md"
          commit-message: "Update LLMs.md"
          base: "main"
