name: Verify LLMs.txt

on:
  pull_request:
    paths:
      - 'python/generate_llms_txt.py'
      - 'LLMs.txt'
      - 'docs/en/**/*.ipynb'
      - 'docs/en/_toc.yml'
  push:
    branches:
      - main
    paths:
      - 'python/generate_llms_txt.py'
      - 'LLMs.txt'
      - 'docs/en/**/*.ipynb'
      - 'docs/en/_toc.yml'

jobs:
  verify-llms-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Generate LLMs.txt
        run: |
          # Run the script to generate a new LLMs.txt file
          uv run python/generate_llms_txt.py
          
          # Compare the files using git diff
          git diff --exit-code LLMs.txt
