name: Verify LLMs.txt

on:
  pull_request:
    paths:
      - 'python/generate_llms_txt.py'
      - 'LLMs.txt'
      - 'docs/en/**/*.ipynb'
      - 'docs/en/_toc.yml'
  push:
    branches:
      - main
    paths:
      - 'python/generate_llms_txt.py'
      - 'LLMs.txt'
      - 'docs/en/**/*.ipynb'
      - 'docs/en/_toc.yml'

jobs:
  verify-llms-txt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-test-environment

      - name: Generate LLMs.txt
        run: |
          # Run the script to generate LLMs.txt
          uv run python/generate_llms_txt.py
          mv LLMs.txt LLMs.txt.generated

      - name: Compare generated file with committed file
        run: |
          if [ ! -f "LLMs.txt" ]; then
            echo "Error: LLMs.txt does not exist in the repository"
            exit 1
          fi
          
          # Compare the files using git diff
          mv LLMs.txt.generated LLMs.txt.new
          cp LLMs.txt LLMs.txt.old
          mv LLMs.txt.new LLMs.txt
          git diff --exit-code LLMs.txt.old LLMs.txt
